### ISSUE TITLE
Create a truffle project and use zeppelin-solidity contracts

### ISSUE THREAD

**Issue by ppoliani** [sportyfi/SportyFiSmartContracts#1]
How about using a tool to manage the project. We can possibly use truffle to organize the project and add migration scripts to manage the smart contract deployments.

Also, most of the functionality can be found in reusable open source smart contracts that are well tested. Zeppelin has a good set of smart contracts that covers most of the functionality needed for a crowdsale.

Also, we should probably update the `solc` version to `0.4.20`

I'm happy to create a PR if you're happy with those suggestions.

**Comment by sportyfi** [comment]
It's crowdsale SmartContract!
